controller_joint_names: ['', 'shoulder_joint', 'elbow_joint', 'wrist_joint', 'knuckle_joint', 'left_gear_joint', 'left_finger_tip_joint', 'right_gear_joint', 'right_finger_tip_joint', 'left_finger_joint', 'right_finger_joint', ]
